In [1]:
import numpy as np

In [2]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10,2,-1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [8]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.logspace(2,4,8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [10]:
np.linspace(2,4,8)

array([2.        , 2.28571429, 2.57142857, 2.85714286, 3.14285714,
       3.42857143, 3.71428571, 4.        ])

In [11]:
np.logspace(2,4,8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [12]:
np.random.rand(2,2,2)

array([[[0.04002322, 0.59933227],
        [0.49206813, 0.12899524]],

       [[0.45253142, 0.70930884],
        [0.58697551, 0.18578486]]])

In [16]:
a=np.random.randint(0,10,size=(5,5))

In [17]:
a

array([[0, 7, 8, 0, 2],
       [9, 9, 6, 0, 7],
       [0, 1, 6, 2, 7],
       [7, 3, 8, 6, 9],
       [3, 1, 1, 5, 5]])

In [18]:
a[:,:]

array([[0, 7, 8, 0, 2],
       [9, 9, 6, 0, 7],
       [0, 1, 6, 2, 7],
       [7, 3, 8, 6, 9],
       [3, 1, 1, 5, 5]])

In [19]:
a = np.zeros((3,3))

In [20]:
b = np.ones((3,3))

In [21]:
np.concatenate([a,b])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.hstack([a,b])

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [24]:
np.vstack([a,b])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.concatenate([a,b],axis=0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.concatenate([a,b],axis=1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [27]:
c = np.random.randint(0,2,size=(5,5))

In [28]:
d = np.random.randint(0,3,size=(5,5))

In [29]:
np.vstack([c,d])

array([[1, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 1, 1],
       [1, 1, 2, 2, 0],
       [2, 2, 0, 0, 2],
       [1, 1, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [2, 2, 0, 2, 0]])

In [30]:
np.hstack([c,d])

array([[1, 1, 0, 0, 0, 1, 1, 2, 2, 0],
       [0, 0, 0, 1, 0, 2, 2, 0, 0, 2],
       [1, 0, 0, 1, 1, 1, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 2, 2, 0, 2, 0]])

In [31]:
k = np.random.randint(0,10,size=(4,10))

In [32]:
d1,d2 = np.vsplit(d,[2])

In [33]:
d1

array([[1, 1, 2, 2, 0],
       [2, 2, 0, 0, 2]])

In [34]:
k

array([[0, 8, 6, 6, 1, 4, 8, 1, 6, 0],
       [9, 5, 6, 9, 1, 1, 6, 8, 6, 7],
       [4, 7, 4, 9, 9, 0, 7, 1, 0, 6],
       [1, 5, 9, 8, 0, 5, 2, 7, 6, 4]])

In [35]:
d1,d2 = np.vsplit(k,[2])

In [36]:
d1

array([[0, 8, 6, 6, 1, 4, 8, 1, 6, 0],
       [9, 5, 6, 9, 1, 1, 6, 8, 6, 7]])

In [37]:
d2

array([[4, 7, 4, 9, 9, 0, 7, 1, 0, 6],
       [1, 5, 9, 8, 0, 5, 2, 7, 6, 4]])

In [38]:
k.ndim

2

In [39]:
k.shape

(4, 10)

In [40]:
k.size

40

In [41]:
a = np.array([1,2,3,4,5,6])

In [42]:
a

array([1, 2, 3, 4, 5, 6])

In [43]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
a.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
a[:,np.newaxis].shape

(5, 1)

In [51]:
a[:,np.newaxis,np.newaxis].shape

(6, 1, 1)

In [52]:
np.sum(a)

21

In [53]:
np.max(a)

6

In [54]:
a = np.random.randint(0,10,size=(3,3))

In [55]:
a

array([[1, 0, 6],
       [5, 8, 0],
       [3, 1, 1]])

In [56]:
np.sum(a,axis=0)

array([9, 9, 7])

In [57]:
np.sum(a,axis=1)

array([ 7, 13,  5])

In [58]:
a = np.array([1,2,3,4,5])

In [59]:
b = np.array([3,4,5,6,7])

In [60]:
a + b

array([ 4,  6,  8, 10, 12])

In [61]:
np.arange(3) + 5

array([5, 6, 7])

In [62]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [65]:
np.arange(3)

array([0, 1, 2])

In [66]:
np.arange(3).reshape(-1,1) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [67]:
a = np.array(([[1,2,3],[4,5,6]]))

In [68]:
b = np.array(([[1,2,3],[4,5,6],[7,8,9]]))

In [69]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [73]:
a = a.reshape(1,2,3)

In [76]:
a

array([[[1, 2, 3],
        [4, 5, 6]]])

In [74]:
b = b.reshape(3,1,3)

In [77]:
b

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [75]:
a + b

array([[[ 2,  4,  6],
        [ 5,  7,  9]],

       [[ 5,  7,  9],
        [ 8, 10, 12]],

       [[ 8, 10, 12],
        [11, 13, 15]]])

In [78]:
a = np.array([[1,1],[3,2]])

In [81]:
b = np.array([[2,3],[4,5],[7,8]])

In [82]:
a

array([[1, 1],
       [3, 2]])

In [83]:
b

array([[2, 3],
       [4, 5],
       [7, 8]])

In [85]:
a = a.reshape(1,2,2)

In [86]:
a

array([[[1, 1],
        [3, 2]]])

In [87]:
b = b.reshape(3,2,1)

In [88]:
b

array([[[2],
        [3]],

       [[4],
        [5]],

       [[7],
        [8]]])

In [89]:
a.shape

(1, 2, 2)

In [90]:
b.shape

(3, 2, 1)

In [91]:
a - b

array([[[-1, -1],
        [ 0, -1]],

       [[-3, -3],
        [-2, -3]],

       [[-6, -6],
        [-5, -6]]])

In [92]:
a+b

array([[[ 3,  3],
        [ 6,  5]],

       [[ 5,  5],
        [ 8,  7]],

       [[ 8,  8],
        [11, 10]]])